spring:
  application:
    name: api-gateway

server:
  port: ${API_GATEWAY_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always