spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: identity-service
              uri: http://identity-service:8081
              predicates:
                - Path=/api/auth/**

            - id: event-service
              uri: http://event-service:8082
              predicates:
                - Path=/api/events/**
              filters:
                - AddRequestHeader=X-Gateway-Request, processed
                - AddResponseHeader=X-Gateway-Response, processed

            - id: booking-service
              uri: http://booking-service:8083
              predicates:
                - Path=/api/bookings/**

            - id: payment-service
              uri: http://payment-service:8084
              predicates:
                - Path=/api/payments/**

            - id: notification-service
              uri: http://notification-service:8085
              predicates:
                - Path=/api/notifications/**

server:
  port: ${API_GATEWAY_PORT:8080}

jwt:
  public-key-path: ${JWT_PUBLIC_KEY_PATH:../infrastructure/keys/public.pem}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always