spring:
  application:
    name: booking-service

  datasource:
    url: ${BOOKING_DB_URL}
    username: ${BOOKING_DB_USER}
    password: ${BOOKING_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

    show-sql: ${JPA_SHOW_SQL:true}

    properties:
      hibernate:
        format_sql: true

server:
  port: ${BOOKING_SERVICE_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always