spring:
  application:
    name: payment-service

  datasource:
    url: ${PAYMENT_DB_URL}
    username: ${PAYMENT_DB_USER}
    password: ${PAYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

    show-sql: ${JPA_SHOW_SQL:true}

    properties:
      hibernate:
        format_sql: true

server:
  port: ${PAYMENT_SERVICE_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always